name: Miscellaneous CI
on:
  workflow_dispatch:
  workflow_call:

jobs:
  miscellaneous:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Set HAXEPATH
        run: echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Packages
        run: |
          sudo apt-get install g++ g++-multilib gcc-multilib

      - name: Install Haxe dependencies
        run: |
          haxelib git hxcpp https://github.com/FunkinCrew/hxcpp --quiet
          haxelib git openfl https://github.com/FunkinCrew/openfl --quiet
          haxelib install format --quiet
          haxelib install svg --quiet
          haxelib install hxp --quiet

      - name: Configure Lime
        run: haxelib dev lime ${{ github.workspace }}

      - name: Rebuild Miscellaneous
        run: |
          haxelib run lime rebuild hxcpp
          haxelib run lime rebuild tools

      - name: Upload Artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: Miscellaneous
          path: |
            tools/tools.n
            run.n
            svg.n
          if-no-files-found: error
